export enum TipoEndereco {
  TRANSPORTADORA = 'TRANSPORTADORA',

  EMBARCADOR = 'EMBARCADOR',

  NOTA_FISCAL_COLETA_ORIGEM = 'NOTA_FISCAL_COLETA_ORIGEM',

  NOTA_FISCAL_COLETA_DESTINO = 'NOTA_FISCAL_COLETA_DESTINO',

  SOLICITACAO_COLETA_ORIGEM = 'SOLICITACAO_COLETA_ORIGEM',

  SOLICITACAO_COLETA_DESTINO = 'SOLICITACAO_COLETA_DESTINO',
}
